version: '3.8'
services:
  app:
    image: crud-template-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/crud_template
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Mysql
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: crud_template
      MYSQL_ROOT_PASSWORD: Mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
